/// Flutter icons MainIcons
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MainIcons
///      fonts:
///       - asset: fonts/MainIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class MainIcons {
  MainIcons._();

  static const _kFontFam = 'MainIcons';
  static const String? _kFontPkg = null;

  static const IconData ic_chevron_right =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_drawer_menu =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_rounded_person =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_bell =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_category =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_send_mail =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_verified =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_filter =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_chart =
      IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
