/// Flutter icons SignUpIcons
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SignUpIcons
///      fonts:
///       - asset: fonts/SignUpIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class SignUpIcons {
  SignUpIcons._();

  static const _kFontFam = 'SignUpIcons';
  static const String? _kFontPkg = null;

  static const IconData ic_fireworks =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_bookmark =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_mail =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_tag =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_down_arrow =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_password =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_person =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_phone =
      IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_eye_open =
      IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_eye_slash =
      IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
